"""empty message

Revision ID: 82986fa7aef0
Revises: 066b188edae1
Create Date: 2018-06-09 01:45:33.706683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82986fa7aef0'
down_revision = '066b188edae1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_adminenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_adminenticated')
    # ### end Alembic commands ###
