"""empty message

Revision ID: 956fbdc375b8
Revises: 82986fa7aef0
Create Date: 2018-06-09 18:49:05.165473

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '956fbdc375b8'
down_revision = '82986fa7aef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('real_name', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'real_name')
    # ### end Alembic commands ###
